# Carregamentos e junção das tabelas

Isntalando bibliotecas

In [ ]:
pip install pandas

In [ ]:
pip install pandas openpyxl

Importando bibliotecas

In [22]:
import pandas as pd

In [ ]:
# Lendo com separador ; e tratando vírgula como decimal
df1 = pd.read_csv(
    r"C:\Users\Carlos\Desktop\Dashboard python\Dados\4_1_meta_2017.csv",
    sep=";",              # separador correto
    decimal=",",          # vírgula como separador decimal
    on_bad_lines="skip",  # ignora linhas quebradas
    encoding="utf-8"      # garante leitura correta
)

df2 = pd.read_csv(
    r"C:\Users\Carlos\Desktop\Dashboard python\Dados\4_1_meta_2018.csv",
    sep=";", decimal=",", on_bad_lines="skip", encoding="utf-8"
)

df3 = pd.read_csv(
    r"C:\Users\Carlos\Desktop\Dashboard python\Dados\4_1_meta_2019.csv",
    sep=";", decimal=",", on_bad_lines="skip", encoding="utf-8"
)

In [37]:
# Concatenando as três bases
df_final = pd.concat([df1, df2, df3], ignore_index=True)

# Substituir '##' por vazio ou por NaN
df_final = df_final.replace("##", pd.NA)   # usa NaN (melhor para cálculos)
# Se preferir string vazia, troque por: df_final = df_final.replace("##", "")

# Salvando em um novo arquivo
df_final.to_csv(
    r"C:\Users\Carlos\Desktop\Dashboard python\Dados\base_final.csv",
    sep=";", decimal=",", index=False, encoding="utf-8"
)

In [25]:
df_final

,DATA,TOTAL_VENDA,CAIXA_VENDEDOR,COD_FORMA_PGTO,VALOR_CANCELADO,NUMERO_CUPOM_FISCAL
0,2017-02-01 00:00:00.000,149.0,UGB,1,0.0,5698
1,2017-02-01 00:00:00.000,162.0,UGB,1,0.0,5699
2,2017-02-01 00:00:00.000,124.0,UGB,4,0.0,5700
3,2017-02-01 00:00:00.000,270.0,UGB,1,0.0,5701
4,2017-02-01 00:00:00.000,284.0,UGB,1,0.0,5702
...,...,...,...,...,...,...
10027,2019-01-13 00:00:00.000,561.0,USV,3,43.0,2557
10028,2019-01-21 00:00:00.000,428.0,USV,1,34.9,2827
10029,2019-02-09 00:00:00.000,367.0,USV,1,28.0,3412
10030,2019-01-24 00:00:00.000,576.0,USV,1,0.0,2924
10031,2019-01-18 00:00:00.000,563.0,USV,##,31.0,2724

In [ ]:
pip install streamlit

In [ ]:
pip install plotly

In [35]:
import streamlit as st

In [30]:
import plotly.express as px

In [36]:
st.set_page_config(layout="wide")

2026-09-24 12:21:39.935 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [42]:
df_final['DATA']

0        2017-02-01 00:00:00.000
1        2017-02-01 00:00:00.000
2        2017-02-01 00:00:00.000
3        2017-02-01 00:00:00.000
4        2017-02-01 00:00:00.000
                  ...
10027    2019-01-13 00:00:00.000
10028    2019-01-21 00:00:00.000
10029    2019-02-09 00:00:00.000
10030    2019-01-24 00:00:00.000
10031    2019-01-18 00:00:00.000
Name: DATA, Length: 10032, dtype: str

Trantando o campo data

In [43]:
df_final['DATA'] = pd.to_datetime(df_final['DATA'])

Campo data Tratado

In [44]:
df_final["DATA"]

0       2017-02-01
1       2017-02-01
2       2017-02-01
3       2017-02-01
4       2017-02-01
           ...
10027   2019-01-13
10028   2019-01-21
10029   2019-02-09
10030   2019-01-24
10031   2019-01-18
Name: DATA, Length: 10032, dtype: datetime64[us]

Ordenando por data

In [50]:
df_final = df_final.sort_values(by="DATA")

Criando uma nova coluna para vizualizar os dados por mes e ano

In [53]:
df_final["Month"] = df_final["DATA"].apply(lambda x: str(x.year) + "-" + str(x.month))

DF com a coluna Month Adicionada

In [54]:
df_final

,DATA,TOTAL_VENDA,CAIXA_VENDEDOR,COD_FORMA_PGTO,VALOR_CANCELADO,NUMERO_CUPOM_FISCAL,Month
114,2017-01-02,194.0,8080,4,0.0,5812,2017-1
129,2017-01-02,258.0,8080,NaN,0.0,5827,2017-1
128,2017-01-02,193.0,8080,NaN,0.0,5826,2017-1
127,2017-01-02,220.0,8080,4,0.0,5825,2017-1
126,2017-01-02,283.0,8080,4,0.0,5824,2017-1
...,...,...,...,...,...,...,...
9706,2019-03-29,563.0,VRO,1,0.0,3422,2019-3
9958,2019-03-29,164.0,VRO,1,14.9,3419,2019-3
9963,2019-03-29,583.0,VRO,1,32.9,3420,2019-3
8456,2019-05-17,485.0,VRO,3,37.0,3424,2019-5
9945,2019-12-08,643.0,309,1,60.0,3425,2019-12

In [55]:
Month = st.sidebar._selectbox('Mês',df_final["Month"].unique())

2026-09-24 13:00:37.002 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-24 13:00:37.016 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-24 13:00:37.017 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-09-24 13:00:37.030 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-24 13:00:37.145
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Carlos\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-09-24 13:00:37.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-24 13:00:37.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Qual o faturamento por Vendedor ?

In [ ]:
fe