Importando bibliotecas

In [17]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

Carregando DF

In [49]:
df = pd.read_csv(r'C:\Users\Carlos\Desktop\Dashboard python\Dados\dataset_vendas.csv')

Primeiros e ultimos registros do DF

In [50]:
df

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,Pago,1,Abr,Televisão,R$ 7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,Pago,10,Ago,Televisão,R$ 11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,Pago,20,Set,Website,R$ 12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,Pago,23,Set,Facebook,R$ 15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,Pago,11,Set,Televisão,R$ 25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo
...,...,...,...,...,...,...,...,...,...,...,...,...
1232,Não pago,18,Nov,Facebook,R$ 0,2,12:55,NaN,NaN,A1,Equipe 4,Theo
1233,Não pago,24,Nov,WhatsApp,R$ 0,2,12:55,NaN,NaN,A7,Equipe 2,Heitor
1234,Não pago,9,Dez,Televisão,R$ 0,1,12:55,NaN,NaN,A4,Equipe 2,Laura
1235,Não pago,11,Fev,Facebook,R$ 0,2,12:55,NaN,NaN,B18,Equipe 2,Laura
1236,Não pago,12,Mar,Televisão,R$ 0,2,12:55,NaN,NaN,B18,Equipe 3,Sophia

Tratando os dados

In [51]:
meses_map = {
    'Jan': int(1),
    'Fev': int(2),
    'Mar': int(3),
    'Abr': int(4),
    'Mai': int(5),
    'Jun': int(6),
    'Jul': int(7),
    'Ago': int(8),
    'Set': int(9),
    'Out': int(10),
    'Nov': int(11),
    'Dez': int(12)
}

df['Mês'] = df['Mês'].map(meses_map)

In [52]:
df ['Valor Pago'] = df ['Valor Pago'].str.lstrip('R$ ').astype(int)

In [53]:
status_map = {
    'Pago': int(1),
    'Não pago': int(0),
}

df['Status de Pagamento'] = df['Status de Pagamento'].map(status_map)

In [54]:
df

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,1,1,4,Televisão,7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,1,10,8,Televisão,11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,1,20,9,Website,12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,1,23,9,Facebook,15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,1,11,9,Televisão,25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo
...,...,...,...,...,...,...,...,...,...,...,...,...
1232,0,18,11,Facebook,0,2,12:55,NaN,NaN,A1,Equipe 4,Theo
1233,0,24,11,WhatsApp,0,2,12:55,NaN,NaN,A7,Equipe 2,Heitor
1234,0,9,12,Televisão,0,1,12:55,NaN,NaN,A4,Equipe 2,Laura
1235,0,11,2,Facebook,0,2,12:55,NaN,NaN,B18,Equipe 2,Laura
1236,0,12,3,Televisão,0,2,12:55,NaN,NaN,B18,Equipe 3,Sophia

Entendendo os tipos de dados

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1237 entries, 0 to 1236
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Status de Pagamento    1237 non-null   int64
 1   Dia                    1237 non-null   int64
 2   Mês                    1237 non-null   int64
 3   Meio de Propaganda     1237 non-null   str
 4   Valor Pago             1237 non-null   int64
 5   Chamadas Realizadas    1237 non-null   int64
 6   Duração da chamada     1237 non-null   str
 7   Modelo de Treinamento  926 non-null    str
 8   Nivel de Treinamento   926 non-null    str
 9   Código de Área         1237 non-null   str
 10  Equipe                 1237 non-null   str
 11  Consultor              1237 non-null   str
dtypes: int64(5), str(7)
memory usage: 160.8 KB